stages:
  - test
  - doc

services:
  - postgres

job:
    when: test
    image: continuumio/miniconda3:latest
    variables:
        DB_HOST: "postgres"
        DB_USER: "postgres"
        PGPASSWORD: ""
        DB_NAME: "molecdb"
    before_script:
      - conda create -n molecdb python=3.6
      - source activate molecdb
      - apt-get update
      - apt-get upgrade -y
      - apt-get install -y postgresql-client libxrender1
      - ./pgsql/setup.sh
      - pip install coverage pytest alembic
      - python setup.py install
      - alembic -c tests/alembic.ini.test upgrade head
    script:
      - python setup.py test
      - coverage run --source goldmine -m py.test
      - coverage report

schemacrawler:
    when: doc
    image: schemacrawler/schemacrawler
    variables:
        DB_HOST: "postgres"
        DB_USER: "postgres"
        PGPASSWORD: ""
        DB_NAME: "molecdb"
    script:
      - schemacrawler -server=postgres -user=portgres -host=postgres -database=molecdb -password='' -c=schema -fmt=scdot -o=schema.graphviz
    artifacts:
      paths:
        schema.graphviz


    
