FROM tiangolo/uvicorn-gunicorn:python3.7

LABEL maintainer="Ian Benlolo <ian.benlolo@gmail.com> Theophile Gaudin <>"

COPY setup.* ./

COPY molar/ /

RUN pip install --upgrade pip && pip install --no-cache-dir fastapi && pip install -e .



ENTRYPOINT ["/molar/backend/entrypoint.sh"]


