version: '3'

services:
    postgres:
      restart: always
      image: 'tgaudin/postgresql-pgtap'
      ports:
        - "5432:5432"
      volumes:
        - "./data:/var/lib/postgresql/data"
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    docs:
      restart: always
      image: 'nginx:mainline-alpine'
      ports:
        - "80:80"
      volumes:
        - "./docs/_build/html/:/usr/share/nginx/html:ro"
