version: '3'

services:
    postgres:
      restart: always
      image: 'tgaudin/postgresql-pgtap'
      shm_size: '4gb'
      ports:
        - "5432:5432"
      volumes:
        - "./data:/var/lib/postgresql/data"
      environment:
        POSTGRES_HOST_AUTH_METHOD: trust
